model:
  class_path: src.training.modules.FinetuningModuleDenseHead
  init_args:
    model:
      class_path: src.ribonanzanet.RibonanzaNet
    out_size: 2
    pooling:
      type: 'mean'
      dim: -2
    ckpt_dir: ${RN_COV_CKPT}

trainer:
  precision: 16-mixed
  accelerator: auto
  devices: 1
  callbacks:
    - class_path: src.data.writing.HDF5PredictionWriter
      init_args:
        variable_name: reads
        write_interval: batch

data:
  class_path: src.data.datamodules.HDF5DataModule
  init_args:
    target_variables:
      - [[2A3, DMS], target]
    input_variables:
      - [[sequence], x]
